name: Deploy

on:
  workflow_dispatch:  # This enables manual triggering of the workflow

permissions:
      id-token: write # This is required for aws oidc connection
      contents: read # This is required for actions/checkout

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    environment: aws
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: Github-OIDC-Lambda

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Retrieve Wiz credentials from AWS Secrets Manager
        id: get-wiz-credentials
        run: |
          WIZ_CREDS=$(aws secretsmanager get-secret-value --secret-id Wiz/CICD --query SecretString --output text)
          echo "Wiz credentials fetched: $WIZ_CREDS"
          echo "$WIZ_CREDS" > wiz_creds.json
          export WIZ_CLIENT_ID=$(jq -r .WIZ_CLIENT_ID wiz_creds.json)
          export WIZ_CLIENT_SECRET=$(jq -r .WIZ_CLIENT_SECRET wiz_creds.json)
          echo "WIZ_CLIENT_ID=${WIZ_CLIENT_ID}" >> $GITHUB_ENV
          echo "WIZ_CLIENT_SECRET=${WIZ_CLIENT_SECRET}" >> $GITHUB_ENV
          ls

      
      - name: npm install
        env:
          CI: true
        run: |
          npm install
      - name: build
        run: |
          #npx ncc build index.ts
          zip -j deploy.zip ./dist/*
          #aws lambda update-function-code --function-name=github-action-lambda-cicd-sample --zip-file=fileb://deploy.zip

      - name: Download Wiz CLI
        run: curl -o wizcli https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64 && chmod +x wizcli
  
      - name: Authenticate to Wiz
        run: ./wizcli auth --id "$WIZ_CLIENT_ID" --secret "$WIZ_CLIENT_SECRET"
        #env:
        #  WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
        #  WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
  
      - name: Run wiz-cli directory scan
        run: ./wizcli dir scan --path . --policy "Revvity Data Security policy,Revvity Secret Management Policy,Revvity Vulnerability Management policy"
  
      - name: Run wiz-cli IAC scan
        run: ./wizcli iac scan --path . --policy "Revvity Infrastructure As Code Policy"

      - name: deploy
        run: |
          aws lambda update-function-code --function-name=github-action-lambda-cicd-sample --zip-file=fileb://deploy.zip

