name: Deploy

on:
  workflow_dispatch:  # This enables manual triggering of the workflow

permissions:
      id-token: write # This is required for aws oidc connection
      contents: read # This is required for actions/checkout

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      #- name: deploy
      #  run: |
      #    npx ncc build index.ts
      #    zip -j deploy.zip ./dist/*
      #    aws lambda update-function-code --function-name=github-action-lambda-cicd-sample --zip-file=fileb://deploy.zip
